(() => {
'use strict';
const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false});
let W=0,H=0,DPR=1,time=0,songStart=0,last=performance.now(),screen='title',toastTimer=0,pendingPlacement=null,marketPreviews=[],ready=false;
const assetPromises=new Map();
const camera={x:0,y:20,zoom:.85,autoFit:true,drag:false,moved:false,startX:0,startY:0,baseX:0,baseY:0};
const pointers=new Map(),images=new Map(),music=[],animations=new Map(),spriteCanvases=new Map(),audioBuffers=new Map();
let spriteRegistry=null,tileData=null,audioContext=null,songStartedAt=0,songGeneration=0,songLoading=false;const islandTileCanvases=new Map();
const imagePaths={sky1:'assets/original/gfx/sky01.png',sky2:'assets/original/gfx/sky02.png',sky3:'assets/original/gfx/sky03.png',castle:'assets/original/gfx/structures/structure_castle01.png',nursery:'assets/original/gfx/structures/structure_nursery.png',breeding:'assets/original/gfx/structures/structure_breeding.png',bakery:'assets/original/gfx/structures/bakeries_sheet.png'};
const monster=(name,code,element,cost,currency='diamonds')=>({name,element,cost,currency,spore:`assets/original/gfx/spore_${code}.png`,track:`01-${code}_Monster_01.ogg`,animation:`monster_${code.toLowerCase()}`,clip:`01-${code}_Monster_01`});
const MONSTERS={
 A:monster('Tweedle','A','AIR',250,'coins'),B:monster('Potbelly','B','PLANT',250,'coins'),C:monster('Noggin','C','EARTH',300,'coins'),D:monster('Toe Jammer','D','WATER',250,'coins'),E:monster('Mammott','E','COLD',300,'coins'),
 AB:monster('Dandidoo','AB','AIR · PLANT',30),AC:monster('Cybop','AC','AIR · EARTH',30),AD:monster('Quibble','AD','AIR · WATER',30),AE:monster('Pango','AE','AIR · COLD',30),BC:monster('Shrubb','BC','PLANT · EARTH',30),BD:monster('Oaktopus','BD','PLANT · WATER',30),BE:monster('Furcorn','BE','PLANT · COLD',30),CD:monster('Fwog','CD','EARTH · WATER',30),CE:monster('Drumpler','CE','EARTH · COLD',30),DE:monster('Maw','DE','WATER · COLD',30),
 ABD:monster('Thumpies','ABD','AIR · PLANT · WATER',50),ABE:monster('Spunge','ABE','AIR · PLANT · COLD',50),ACD:monster('Scups','ACD','AIR · EARTH · WATER',50),ACE:monster('PomPom','ACE','AIR · EARTH · COLD',50),ADE:monster('Congle','ADE','AIR · WATER · COLD',50),BCD:monster('Pummel','BCD','PLANT · EARTH · WATER',50),BCE:monster('Clamble','BCE','PLANT · EARTH · COLD',50),BDE:monster('Bowgart','BDE','PLANT · WATER · COLD',50),CDE:monster('T-Rox','CDE','EARTH · WATER · COLD',50),
 ABDE:monster('Deedge','ABDE','COLD ISLAND QUAD',150),ACDE:monster('Riff','ACDE','AIR ISLAND QUAD',150),BCDE:monster('Entbrat','BCDE','PLANT ISLAND QUAD',150)
};
const ISLANDS={1:{name:'Plant Island',elements:'BCDE'},2:{name:'Cold Island',elements:'ABDE'},3:{name:'Air Island',elements:'ACDE'}};
function islandAllows(code,island=save.currentIsland||1){const elements=ISLANDS[island].elements;return[...code].every(element=>elements.includes(element))}
const freshSave=()=>({version:3,level:1,xp:0,coins:500,diamonds:20,food:100,sound:true,tutorial:false,currentIsland:1,ownedIslands:[1,2,3],monsters:[],breeding:null,nursery:null,lastCoinTick:Date.now()});
let save=loadSave();
function loadSave(){try{const merged={...freshSave(),...JSON.parse(localStorage.getItem('msm-1.0-web-save')||'{}')};merged.monsters=(merged.monsters||[]).map(monster=>({...monster,island:monster.island||1}));merged.version=3;return merged}catch{return freshSave()}}
function persist(){localStorage.setItem('msm-1.0-web-save',JSON.stringify(save))}
function resize(){const rect=canvas.getBoundingClientRect();DPR=Math.min(devicePixelRatio||1,1.5);W=rect.width;H=rect.height;canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);if(camera.autoFit)camera.zoom=clamp(Math.min(W/1180,(H-105)/680),.48,1)}
addEventListener('resize',resize);resize();
function loadImage(key,path){if(images.has(key))return Promise.resolve(images.get(key));return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{images.set(key,image);resolve(image)};image.onerror=()=>reject(new Error(`Could not load ${path}`));image.src=path})}
async function fetchJson(path){const response=await fetch(path);if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.json()}
function animationDuration(animation){let duration=0;for(const layer of animation.l)for(const frame of layer.f)duration=Math.max(duration,frame[0]);return duration||1}
function valueAt(frames,time,immediateIndex,valueIndex,fallback){const valid=frames.filter(frame=>frame[immediateIndex]!==-1);if(!valid.length)return fallback;let previous=null,next=null;for(const frame of valid){if(frame[0]<=time)previous=frame;else{next=frame;break}}if(!previous)return valid[0][valueIndex];if(previous[immediateIndex]===0&&next&&next[0]>previous[0]){const ratio=(time-previous[0])/(next[0]-previous[0]);return previous[valueIndex]+(next[valueIndex]-previous[valueIndex])*ratio}return previous[valueIndex]}
function spriteAt(frames,time){const changes=[];let last='';for(const frame of frames)if(frame[11]&&frame[11]!==last){last=frame[11];changes.push(frame)}if(!changes.length)return'';let previous=null,next=null;for(const frame of changes){if(frame[0]<=time)previous=frame;else{next=frame;break}}if(!previous)return changes[0][11];if(!next)return previous[11];const a=previous[11].match(/^(.*?)(\d+)$/),b=next[11].match(/^(.*?)(\d+)$/);if(a&&b&&a[1]===b[1]&&a[1].endsWith('_')){const from=Number(a[2]),to=Number(b[2]),gap=to-from;if(gap>1){const ratio=clamp((time-previous[0])/(next[0]-previous[0]),0,.9999),value=from+Math.floor(ratio*gap),name=a[1]+String(value).padStart(a[2].length,'0');if(spriteRegistry?.sprites[name])return name}}return previous[11]}
function layerState(layer,time){const frames=layer.f;return{x:valueAt(frames,time,1,2,0),y:valueAt(frames,time,1,3,0),sx:valueAt(frames,time,4,5,100)/100,sy:valueAt(frames,time,4,6,100)/100,rotation:valueAt(frames,time,7,8,0),opacity:clamp(valueAt(frames,time,9,10,100)/100,0,1),sprite:spriteAt(frames,time)}}
function multiplyMatrix(parent,local){return[parent[0]*local[0]+parent[2]*local[1],parent[1]*local[0]+parent[3]*local[1],parent[0]*local[2]+parent[2]*local[3],parent[1]*local[2]+parent[3]*local[3],parent[0]*local[4]+parent[2]*local[5]+parent[4],parent[1]*local[4]+parent[3]*local[5]+parent[5]]}
function animationStates(animation,seconds){const duration=animation._duration||(animation._duration=animationDuration(animation)),localTime=((seconds%duration)+duration)%duration,states=[];const resolve=index=>{if(states[index])return states[index];const layer=animation.l[index],state=layerState(layer,localTime),angle=state.rotation*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle),a=state.sx*cos,b=state.sx*sin,c=-state.sy*sin,d=state.sy*cos,local=[a,b,c,d,state.x-(a*layer.a[0]+c*layer.a[1]),state.y-(b*layer.a[0]+d*layer.a[1])],matrix=layer.p>=0?multiplyMatrix(resolve(layer.p).matrix,local):local;return states[index]={...state,matrix}};for(let index=0;index<animation.l.length;index++)resolve(index);return states}
function spriteCanvas(name){if(spriteCanvases.has(name))return spriteCanvases.get(name);const sprite=spriteRegistry?.sprites[name];if(!sprite)return null;const atlas=images.get(`atlas:${sprite.atlas}`);if(!atlas)return null;const canvas=document.createElement('canvas');canvas.width=sprite.originalW;canvas.height=sprite.originalH;const context=canvas.getContext('2d');if(sprite.rotated){context.save();context.translate(sprite.offsetX,sprite.offsetY);context.translate(0,sprite.w);context.rotate(-Math.PI/2);context.drawImage(atlas,sprite.x,sprite.y,sprite.w,sprite.h,0,0,sprite.w,sprite.h);context.restore()}else context.drawImage(atlas,sprite.x,sprite.y,sprite.w,sprite.h,sprite.offsetX,sprite.offsetY,sprite.w,sprite.h);spriteCanvases.set(name,canvas);return canvas}
function drawAnimation(key,clip,x,y,scale,seconds,context=ctx){const payload=animations.get(key);if(!payload)return false;const suffix=String(clip||'').replace(/^\d\d-/,''),animation=payload.animations.find(item=>item.n===clip)||payload.animations.find(item=>suffix&&item.n.endsWith(suffix))||payload.animations[0];if(!animation)return false;const states=animationStates(animation,seconds);context.save();context.translate(x-animation.w*scale/2,y-animation.h*scale/2);context.scale(scale,scale);for(let index=animation.l.length-1;index>=0;index--){const state=states[index],sprite=state.sprite?spriteCanvas(state.sprite):images.get(`direct:${key}`);if(!sprite||state.opacity<=0)continue;context.save();context.transform(...state.matrix);context.globalAlpha*=state.opacity;context.drawImage(sprite,0,0);context.restore()}context.restore();return true}
function buildIslandTiles(index){const grid=tileData.grid,island=tileData.islands[String(index)],atlas=images.get(`tile-atlas:${index}`),canvas=document.createElement('canvas');canvas.width=3744;canvas.height=1872;const context=canvas.getContext('2d'),halfW=grid.tileWidth/2,halfH=grid.tileHeight/2;for(const [name,column,row] of grid.entries){const sprite=island.sprites[name];if(!sprite)continue;const x=(column+row+1)*halfW,y=(grid.rows+row-column)*halfH;context.drawImage(atlas,sprite[0],sprite[1],sprite[2],sprite[3],x-sprite[2]/2,y-sprite[3]/2,sprite[2],sprite[3])}islandTileCanvases.set(index,canvas)}
function loadStatus(message){const status=$('#loadStatus');if(status)status.textContent=message}
async function ensureAnimation(key){if(animations.has(key))return animations.get(key);if(assetPromises.has(`animation:${key}`))return assetPromises.get(`animation:${key}`);const promise=fetchJson(`assets/data/animations/${key}.json`).then(async payload=>{animations.set(key,payload);if(payload.sheet.toLowerCase().endsWith('.xml')){const atlas=payload.sheet.replace(/\.xml$/i,''),path=spriteRegistry.atlases[atlas];if(!path)throw new Error(`Missing atlas ${atlas}`);await loadImage(`atlas:${atlas}`,path)}else{const derived={monster_acd:'assets/derived/monsters/ACD.png',monster_acde:'assets/derived/monsters/ACDE.png'}[key];await loadImage(`direct:${key}`,derived||`assets/original/${payload.sheet}`)}return payload});assetPromises.set(`animation:${key}`,promise);return promise}
async function ensureIslandAssets(index){if(assetPromises.has(`island:${index}`))return assetPromises.get(`island:${index}`);const promise=(async()=>{const monsterEntries=Object.entries(MONSTERS).filter(([code])=>islandAllows(code,index)),keys=[`island0${index}`,'structure_nursery','structure_breeding','bakeries',...monsterEntries.map(([,monster])=>monster.animation)];loadStatus(`Loading ${ISLANDS[index].name} and ${monsterEntries.length} real monsters…`);await Promise.all([...new Set(keys)].map(ensureAnimation));await Promise.all(monsterEntries.map(([code,monster])=>loadImage(`spore-${code}`,monster.spore)));await loadImage(`tile-atlas:${index}`,tileData.islands[String(index)].image);if(!islandTileCanvases.has(index))buildIslandTiles(index)})();assetPromises.set(`island:${index}`,promise);return promise}
async function boot(){
 loadStatus('Reading original 1.0 sprite and island data…');
 [spriteRegistry,tileData]=await Promise.all([fetchJson('assets/data/sprites.json?build=7'),fetchJson('assets/data/island-tiles.json?build=7')]);
 await Promise.all(Object.entries(imagePaths).map(([key,path])=>loadImage(key,path)));
 await ensureIslandAssets(save.currentIsland||1);updateHud();ready=true;$('#playButton').disabled=false;$('#playButton').textContent='PLAY OFFLINE';loadStatus('Ready — real monsters, island graphics and animation data loaded.');requestAnimationFrame(frame)
}
function toast(message){const element=$('#toast');element.textContent=message;element.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>element.classList.remove('show'),1800)}
function playSfx(file,volume=.7){if(!save.sound)return;const audio=new Audio(`assets/original/audio/sfx/${file}`);audio.volume=volume;audio.play().catch(()=>{})}
function stopMusic(){songGeneration++;songLoading=false;while(music.length){const item=music.pop();try{item.stop?item.stop():item.pause()}catch{}}songStartedAt=0}
async function audioBuffer(file){if(audioBuffers.has(file))return audioBuffers.get(file);const promise=fetch(`assets/original/audio/music/${file}`).then(response=>{if(!response.ok)throw new Error(`${file}: HTTP ${response.status}`);return response.arrayBuffer()}).then(buffer=>audioContext.decodeAudioData(buffer));audioBuffers.set(file,promise);return promise}
function songTime(){if(songLoading)return 0;return audioContext&&songStartedAt?Math.max(0,audioContext.currentTime-songStartedAt):Math.max(0,time-songStart)}
async function rebuildSong(){stopMusic();songStart=time;const generation=++songGeneration;if(!save.sound||screen!=='island')return;audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)();await audioContext.resume();const prefix=String(save.currentIsland||1).padStart(2,'0'),files=[`${prefix}-Bass_01.ogg`,...new Set(save.monsters.filter(monster=>(monster.island||1)===(save.currentIsland||1)&&!monster.muted).map(monster=>`${prefix}-${monster.code}_Monster_01.ogg`))];songLoading=true;try{const buffers=await Promise.all(files.map(audioBuffer));if(generation!==songGeneration)return;const start=audioContext.currentTime+.08;songStartedAt=start;songLoading=false;buffers.forEach((buffer,index)=>{const source=audioContext.createBufferSource(),gain=audioContext.createGain();source.buffer=buffer;source.loop=true;gain.gain.value=files[index].includes('Bass')?.5:.72;source.connect(gain).connect(audioContext.destination);source.start(start);music.push(source)})}catch(error){console.warn('Synchronized audio fallback:',error.message);songLoading=false;if(generation!==songGeneration)return;for(const file of files){const audio=new Audio(`assets/original/audio/music/${file}`);audio.loop=true;audio.volume=file.includes('Bass')?.5:.72;audio.currentTime=0;audio.play().catch(()=>{});music.push(audio)}}}
function updateHud(){$('#level').textContent=save.level;$('#coins').textContent=Math.floor(save.coins);$('#diamonds').textContent=save.diamonds;$('#food').textContent=save.food;$('#xpBar').style.width=`${save.xp%100}%`;$('#soundButton').textContent=save.sound?'♫':'×'}
function screenToWorld(x,y){return{x:(x-W/2)/camera.zoom+camera.x,y:(y-H/2)/camera.zoom+camera.y}}
function worldToScreen(x,y){return{x:(x-camera.x)*camera.zoom+W/2,y:(y-camera.y)*camera.zoom+H/2}}
function drawCover(image,x,y,width,height){const scale=Math.max(width/image.width,height/image.height),sw=width/scale,sh=height/scale;ctx.drawImage(image,(image.width-sw)/2,(image.height-sh)/2,sw,sh,x,y,width,height)}
function drawWorldImage(image,x,y,width,height,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(image,x-width/2,y-height/2,width,height);ctx.restore()}
function renderIsland(){
 drawCover(images.get(`sky${save.currentIsland||1}`),0,0,W,H);ctx.fillStyle='#d7f1f4aa';ctx.fillRect(0,0,W,H);
 ctx.save();ctx.translate(W/2-camera.x*camera.zoom,H/2-camera.y*camera.zoom);ctx.scale(camera.zoom,camera.zoom);
 // The native island is a 45-layer AEAnim composite plus the original
 // 39×39, 950-tile isometric grass grid—not a synthetic ellipse.
 const islandIndex=save.currentIsland||1,islandKey=`island0${islandIndex}`,islandTiles=islandTileCanvases.get(islandIndex);
 drawAnimation(islandKey,islandIndex===1?'island01_loop01':'Comp 1',0,42,.27,time);
 if(islandTiles)ctx.drawImage(islandTiles,-3744*.27/2,42-1872*.27/2,3744*.27,1872*.27);
 const nurseryClip=save.nursery?(Date.now()>=save.nursery.readyAt?'structure_nursery_finished':'structure_nursery_lit'):'structure_nursery',prefix=String(save.currentIsland||1).padStart(2,'0');
 const drawables=[
  {y:-105,draw:()=>drawWorldImage(images.get('castle'),-80,-105,230,230)},
  {y:-92,draw:()=>drawAnimation('structure_nursery',nurseryClip,145,-92,.42,time)},
  {y:-45,draw:()=>drawAnimation('structure_breeding',save.breeding?'structure_breeding_active':'structure_breeding',285,-45,.40,time)},
  {y:55,draw:()=>drawAnimation('bakeries','structure_bakery_01_closed',-285,55,.48,time)}
 ];
 for(const monster of save.monsters.filter(item=>(item.island||1)===(save.currentIsland||1)))drawables.push({y:monster.y,x:monster.x,draw:()=>{const def=MONSTERS[monster.code],clip=`${prefix}-${monster.code}_Monster_01`;ctx.save();drawAnimation(def.animation,clip,monster.x,monster.y,.55,songTime());if(monster.readyCoins>=1){ctx.beginPath();ctx.arc(monster.x+31,monster.y-45,18,0,Math.PI*2);ctx.fillStyle='#f4be2b';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#5d3d12';ctx.font='900 13px Arial';ctx.textAlign='center';ctx.fillText(Math.floor(monster.readyCoins),monster.x+31,monster.y-40)}ctx.restore()}});
 drawables.sort((a,b)=>a.y-b.y||(a.x||0)-(b.x||0));for(const drawable of drawables)drawable.draw();
 if(pendingPlacement){const p=placementPoint(screenToWorld(pendingPlacement.x,pendingPlacement.y),pendingPlacement.movingId),prefix=String(save.currentIsland||1).padStart(2,'0'),def=MONSTERS[pendingPlacement.code];ctx.globalAlpha=.7;drawAnimation(def.animation,`${prefix}-${pendingPlacement.code}_Monster_01`,p.x,p.y,.55,songTime());ctx.globalAlpha=1}
 ctx.restore();
}
function renderTitleBackdrop(){drawCover(images.get('sky1'),0,0,W,H)}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;time+=dt;ctx.setTransform(DPR,0,0,DPR,0,0);tickEconomy();if(screen==='island')renderIsland();else renderTitleBackdrop();renderMarketPreviews();requestAnimationFrame(frame)}
function tickEconomy(){const now=Date.now(),elapsed=(now-save.lastCoinTick)/1000;if(elapsed<1)return;save.lastCoinTick=now;for(const monster of save.monsters){monster.level=monster.level||1;monster.happiness=monster.happiness??50;const rate=monster.level*(.5+monster.happiness/100);monster.readyCoins=Math.min(25+monster.level*10,(monster.readyCoins||0)+elapsed/12*rate)}persist()}
function monsterAt(point){let best=null,distance=75;for(const monster of save.monsters.filter(item=>(item.island||1)===(save.currentIsland||1))){const d=Math.hypot(point.x-monster.x,point.y-monster.y);if(d<distance){best=monster;distance=d}}return best}
function collectMonster(monster){const amount=Math.floor(monster.readyCoins||0);if(amount<1)return false;monster.readyCoins-=amount;save.coins+=amount;persist();updateHud();playSfx('collect_coins.wav');toast(`+${amount} COINS`);return true}
function showMonster(monster){const def=MONSTERS[monster.code];monster.level=monster.level||1;monster.meals=monster.meals||0;monster.happiness=monster.happiness??50;const foodCost=monster.level*5;openPanel(def.name.toUpperCase(),`<div class="monster-info"><canvas id="monsterInfoPreview" width="200" height="200"></canvas><h3>LEVEL ${monster.level} · HAPPINESS ${monster.happiness}%</h3><p>Meals this level: ${monster.meals} / 4</p><button class="action" id="feedMonster">FEED · ${foodCost} FOOD</button> <button class="action" id="moveMonster">MOVE</button> <button class="action" id="muteMonster">${monster.muted?'UNMUTE':'MUTE'}</button><button class="action danger" id="sellMonster">SELL · ${Math.max(1,Math.floor(def.cost/2))} ${def.currency==='coins'?'COINS':'DIAMONDS'}</button></div>`);marketPreviews=[{canvas:$('#monsterInfoPreview'),code:monster.code}];$('#feedMonster').onclick=()=>{if(monster.level>=15)return toast('MAX LEVEL');if(save.food<foodCost)return toast('NOT ENOUGH FOOD');save.food-=foodCost;monster.meals++;if(monster.meals>=4){monster.meals=0;monster.level++;save.xp+=10;playSfx('monster_level_up.wav')}persist();updateHud();showMonster(monster);playSfx('feed_monster.wav')};$('#moveMonster').onclick=()=>{pendingPlacement={code:monster.code,movingId:monster.id,x:W/2,y:H/2};closePanel();toast('TAP A NEW LOCATION')};$('#muteMonster').onclick=()=>{monster.muted=!monster.muted;persist();rebuildSong();showMonster(monster)};$('#sellMonster').onclick=()=>{save[def.currency]+=Math.max(1,Math.floor(def.cost/2));save.monsters=save.monsters.filter(item=>item!==monster);persist();updateHud();rebuildSong();closePanel();toast(`${def.name.toUpperCase()} SOLD`)} }
function placementPoint(point,movingId=null){const base={x:clamp(Math.round(point.x/48)*48,-384,384),y:clamp(Math.round(point.y/24)*24,-120,168)},occupied=save.monsters.filter(monster=>(monster.island||1)===(save.currentIsland||1)&&monster.id!==movingId);const candidates=[base];for(let ring=1;ring<=5;ring++)for(const [dx,dy] of [[ring,0],[-ring,0],[0,ring],[0,-ring],[ring,ring],[-ring,ring],[ring,-ring],[-ring,-ring]])candidates.push({x:clamp(base.x+dx*48,-384,384),y:clamp(base.y+dy*24,-120,168)});const structures=[[-80,-105,105],[145,-92,88],[285,-45,92],[-285,55,78]];return candidates.find(candidate=>occupied.every(monster=>Math.hypot(monster.x-candidate.x,(monster.y-candidate.y)*1.6)>72)&&structures.every(([x,y,radius])=>Math.hypot(candidate.x-x,(candidate.y-y)*1.5)>radius))||base}
function placeMonster(code,point){if(pendingPlacement?.movingId){const monster=save.monsters.find(item=>item.id===pendingPlacement.movingId);if(monster){const placed=placementPoint(point,monster.id);monster.x=placed.x;monster.y=placed.y;pendingPlacement=null;persist();toast(`${MONSTERS[monster.code].name.toUpperCase()} MOVED`);return}}const placed=placementPoint(point),monster={id:Date.now(),code,island:save.currentIsland||1,x:placed.x,y:placed.y,phase:0,readyCoins:0,level:1,meals:0,happiness:50,muted:false};save.monsters.push(monster);pendingPlacement=null;save.xp+=12;persist();updateHud();playSfx('hatch_monster.wav');rebuildSong();toast(`${MONSTERS[code].name.toUpperCase()} JOINED THE SONG!`)}
function openPanel(title,html){$('#panelTitle').textContent=title;$('#panelBody').innerHTML=html;$('#panel').hidden=false}
function closePanel(){$('#panel').hidden=true;marketPreviews=[]}
function showMarket(){marketPreviews=[];openPanel(`${ISLANDS[save.currentIsland||1].name.toUpperCase()} MONSTER MARKET`,'<p class="market-note">These are the real animated monsters from the 1.0 IPA. Buying sends the selected monster egg to the Nursery.</p><div class="market-grid"></div>');const grid=$('.market-grid');for(const [code,monster] of Object.entries(MONSTERS).filter(([code])=>islandAllows(code))){const card=document.createElement('article'),symbol=monster.currency==='coins'?'●':'◆';card.className='monster-card';card.innerHTML=`<canvas width="150" height="150" aria-label="Animated ${monster.name}"></canvas><h3>${monster.name}</h3><small>${monster.element}</small><p>${symbol} ${monster.cost}</p><button>BUY ${monster.name.toUpperCase()}</button>`;const preview=$('canvas',card);marketPreviews.push({canvas:preview,code});$('button',card).onclick=()=>{if(save.nursery)return toast('THE NURSERY IS OCCUPIED');if(save[monster.currency]<monster.cost)return toast(`NOT ENOUGH ${monster.currency.toUpperCase()}`);save[monster.currency]-=monster.cost;save.nursery={code,island:save.currentIsland||1,readyAt:Date.now()+15000};persist();updateHud();closePanel();marketPreviews=[];playSfx('egg_ready.wav');toast(`${monster.name.toUpperCase()} EGG SENT TO NURSERY`)};grid.append(card)}}
function renderMarketPreviews(){if(!marketPreviews.length||$('#panel').hidden)return;for(const preview of marketPreviews){const context=preview.canvas.getContext('2d'),width=preview.canvas.width,height=preview.canvas.height;context.clearRect(0,0,width,height);drawAnimation(MONSTERS[preview.code].animation,'Store',width/2,height/2,Math.min(width,height)/150,time,context)}}
function showBake(){openPanel('BAKERY','<div class="list"><article><h3>Small Cupcake</h3><p>Bake 25 food for 50 coins.</p><button class="action" id="bakeNow">BAKE</button></article></div>');$('#bakeNow').onclick=()=>{if(save.coins<50)return toast('NOT ENOUGH COINS');save.coins-=50;save.food+=25;save.xp+=5;persist();updateHud();playSfx('start_baking.wav');toast('+25 FOOD')}}
function sortedCode(code){return[...new Set(code.split(''))].sort((a,b)=>'ABCDE'.indexOf(a)-'ABCDE'.indexOf(b)).join('')}
function showBreed(){
 const now=Date.now(),breeding=save.breeding,nursery=save.nursery,islandMonsterCount=save.monsters.filter(monster=>(monster.island||1)===(save.currentIsland||1)).length,monsterOptions=save.monsters.filter(monster=>(monster.island||1)===(save.currentIsland||1)).map(monster=>`<option value="${monster.id}">${MONSTERS[monster.code].name}</option>`).join('');
 let html='<div class="list">';
 if(breeding){const ready=now>=breeding.readyAt,left=Math.max(0,Math.ceil((breeding.readyAt-now)/1000));html+=`<article><h3>BREEDING: ${MONSTERS[breeding.code].name}</h3><p>${ready?'The egg is ready!':`${left} seconds remaining.`}</p>${ready?'<button class="action" id="collectBreed">COLLECT EGG</button>':''}</article>`}
 else html+=`<article><h3>BREED TWO MONSTERS</h3>${islandMonsterCount>=2?`<select id="parentA">${monsterOptions}</select><select id="parentB">${monsterOptions}</select><button class="action" id="breedNow">BREED</button>`:'<p>Place at least two monsters first.</p>'}</article>`;
 if(nursery){const ready=now>=nursery.readyAt,left=Math.max(0,Math.ceil((nursery.readyAt-now)/1000));html+=`<article><h3>NURSERY: ${MONSTERS[nursery.code].name} EGG</h3><img src="${MONSTERS[nursery.code].spore}" style="width:100px"><p>${ready?'Ready to hatch and place.':`${left} seconds remaining.`}</p>${ready?'<button class="action" id="hatchEgg">HATCH & PLACE</button>':'<button class="action" id="hurryEgg">HURRY · 1 ◆</button>'}</article>`}
 html+='</div>';openPanel('BREEDING & NURSERY',html);
 if($('#breedNow'))$('#breedNow').onclick=()=>{const first=save.monsters.find(monster=>String(monster.id)===$('#parentA').value),second=save.monsters.find(monster=>String(monster.id)===$('#parentB').value);if(!first||!second||first===second)return toast('CHOOSE TWO DIFFERENT MONSTERS');const code=sortedCode(first.code+second.code),result=MONSTERS[code]?code:(Math.random()<.5?first.code:second.code),seconds=Math.max(15,result.length*14);save.breeding={code:result,island:save.currentIsland||1,readyAt:Date.now()+seconds*1000};persist();playSfx('start_breeding.wav');showBreed()};
 if($('#collectBreed'))$('#collectBreed').onclick=()=>{if(save.nursery)return toast('THE NURSERY IS OCCUPIED');save.nursery={code:save.breeding.code,island:save.breeding.island,readyAt:Date.now()+15000};save.breeding=null;persist();playSfx('collect_breeding.wav');showBreed()};
 if($('#hatchEgg'))$('#hatchEgg').onclick=()=>{save.currentIsland=save.nursery.island||save.currentIsland;pendingPlacement={code:save.nursery.code,x:W/2,y:H/2};save.nursery=null;persist();closePanel();playSfx('hatch_monster.wav');toast('TAP THE ISLAND TO PLACE')};
 if($('#hurryEgg'))$('#hurryEgg').onclick=()=>{if(save.diamonds<1)return toast('NOT ENOUGH DIAMONDS');save.diamonds--;save.nursery.readyAt=Date.now();persist();updateHud();showBreed()};
}
function showGoals(){const goals=[['Place your first monster',save.monsters.length>=1],['Build a four-part Plant Island song',new Set(save.monsters.map(m=>m.code)).size>=4],['Collect 100 monster coins',save.coins>=600]];openPanel('GOALS',`<div class="list">${goals.map(([text,done])=>`<article><b>${done?'✓':'○'} ${text}</b></article>`).join('')}</div>`)}
function showIslands(){openPanel('ISLANDS','<div class="island-grid"></div>');const grid=$('.island-grid');for(const [index,island] of Object.entries(ISLANDS)){const card=document.createElement('button');card.className=Number(index)===(save.currentIsland||1)?'active':'';card.innerHTML=`<img src="assets/images/ui/island${index}.png" alt=""><b>${island.name.toUpperCase()}</b><small>${save.monsters.filter(monster=>(monster.island||1)===Number(index)).length} MONSTERS</small>`;card.onclick=async()=>{const target=Number(index);card.disabled=true;toast(`LOADING ${island.name.toUpperCase()}…`);try{await ensureIslandAssets(target);save.currentIsland=target;persist();camera.x=0;camera.y=20;camera.autoFit=true;resize();closePanel();rebuildSong();playSfx('menu_slide.wav');toast(island.name.toUpperCase())}catch(error){console.error(error);toast(`LOAD ERROR: ${error.message}`);card.disabled=false}};grid.append(card)}}
const tutorial=[['WELCOME, MONSTER-HANDLER!','This is an offline reconstruction of the original 2012 client. Your island is saved in this browser.'],['MOVE AROUND','Drag the island to pan. Pinch, use the mouse wheel, or press + and − to zoom.'],['BUY A MONSTER','Open MARKET, buy a monster egg, then tap the island to place it.'],['BUILD THE SONG','Each species adds its original synchronized 1.0 OGG music stem. Use the sound button to mute or restore the mix.'],['COLLECT AND GROW','Tap a monster when its gold bubble appears. Bake food, complete goals and expand your song.']];
function showTutorial(index=0){const [title,text]=tutorial[index];openPanel(`TUTORIAL ${index+1} / ${tutorial.length}`,`<div class="tutorial"><div class="icon">${['🎵','☝️','🥚','🎼','⭐'][index]}</div><h3>${title}</h3><p>${text}</p><p class="dots">${tutorial.map((_,i)=>i===index?'●':'○').join(' ')}</p><button class="action" id="tutorialSkip">SKIP</button> <button class="action" id="tutorialNext">${index===tutorial.length-1?'DONE':'NEXT'}</button></div>`);$('#tutorialSkip').onclick=()=>{save.tutorial=true;persist();closePanel()};$('#tutorialNext').onclick=()=>{if(index===tutorial.length-1){save.tutorial=true;persist();closePanel()}else showTutorial(index+1)}}
canvas.addEventListener('pointerdown',event=>{try{canvas.setPointerCapture(event.pointerId)}catch{}pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});camera.drag=true;camera.moved=false;camera.startX=event.clientX;camera.startY=event.clientY;camera.baseX=camera.x;camera.baseY=camera.y});
canvas.addEventListener('pointermove',event=>{if(!pointers.has(event.pointerId))return;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pendingPlacement){pendingPlacement.x=event.clientX;pendingPlacement.y=event.clientY;return}if(pointers.size===1&&camera.drag){const dx=event.clientX-camera.startX,dy=event.clientY-camera.startY;if(Math.hypot(dx,dy)>5)camera.moved=true;camera.x=clamp(camera.baseX-dx/camera.zoom,-360,360);camera.y=clamp(camera.baseY-dy/camera.zoom,-100,170)}else if(pointers.size>=2){const p=[...pointers.values()],distance=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(!camera.pinch){camera.pinch=distance;camera.pinchZoom=camera.zoom}else{camera.autoFit=false;camera.zoom=clamp(camera.pinchZoom*distance/camera.pinch,.48,1.65)}camera.moved=true}});
function finishPointer(event,cancelled=false){const moved=camera.moved;pointers.delete(event.pointerId);if(pointers.size===1){const p=[...pointers.values()][0];camera.startX=p.x;camera.startY=p.y;camera.baseX=camera.x;camera.baseY=camera.y;camera.pinch=0}else if(!pointers.size){camera.drag=false;camera.pinch=0;if(!cancelled&&!moved&&screen==='island'){if(pendingPlacement)placeMonster(pendingPlacement.code,screenToWorld(event.clientX,event.clientY));else{const monster=monsterAt(screenToWorld(event.clientX,event.clientY));if(monster&&!collectMonster(monster))showMonster(monster)}}}}
canvas.addEventListener('pointerup',event=>finishPointer(event));canvas.addEventListener('pointercancel',event=>finishPointer(event,true));canvas.addEventListener('lostpointercapture',event=>{if(pointers.has(event.pointerId))finishPointer(event,true)});addEventListener('blur',()=>{pointers.clear();camera.drag=false;camera.pinch=0});
canvas.addEventListener('wheel',event=>{if(screen!=='island')return;event.preventDefault();camera.autoFit=false;camera.zoom=clamp(camera.zoom*Math.exp(-event.deltaY*.001),.48,1.65)},{passive:false});
$('#playButton').onclick=()=>{if(!ready)return;screen='island';$('#title').hidden=true;$('#hud').hidden=false;playSfx('menu_click.wav');rebuildSong();if(!save.tutorial)setTimeout(()=>showTutorial(0),400)};
$$('[data-menu]').forEach(button=>button.onclick=()=>{playSfx('menu_click.wav');({market:showMarket,bake:showBake,breed:showBreed,goals:showGoals,islands:showIslands}[button.dataset.menu])()});
$('#closePanel').onclick=closePanel;$('#helpButton').onclick=()=>showTutorial(0);$('#soundButton').onclick=()=>{save.sound=!save.sound;persist();updateHud();rebuildSong()};$('#zoomIn').onclick=()=>{camera.autoFit=false;camera.zoom=clamp(camera.zoom*1.15,.48,1.65)};$('#zoomOut').onclick=()=>{camera.autoFit=false;camera.zoom=clamp(camera.zoom/1.15,.48,1.65)};
window.__msmDebug=()=>({screen,island:save.currentIsland||1,monsters:save.monsters.length,visibleMonsters:save.monsters.filter(monster=>(monster.island||1)===(save.currentIsland||1)).length,coins:save.coins,tracks:music.length,animations:animations.size,camera:{...camera}});
boot().catch(error=>{console.error(error);loadStatus(`LOAD ERROR: ${error.message}`);$('#playButton').textContent='RETRY LOAD';$('#playButton').disabled=false;$('#playButton').onclick=()=>location.reload()});
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
